### ISSUE TITLE
Use of Online Github Pages

### ISSUE THREAD

**Issue by NamVr** [KrishGarg/Project-25#1]
Hi !

It's just a request to use Github pages so that people can view your projects directly without actually downloading the source files?

**Comment by KrishGarg** [comment]
> Hi !
> 
> It's just a request to use Github pages so that people can view your projects directly without actually downloading the source files?

I do have github pages enabled but i don't know why it doesn't show for others. Anyway the direct page links are like https://krishgarg.github.io/(repo name)/

**Comment by NamVr** [comment]
That's great if it works, anyway that was only an advice :)27.07.2020, 22:47, "Krish Garg" <notifications@github.com>:

Hi !
It's just a request to use Github pages so that people can view your projects directly without actually downloading the source files?

I do have github pages enabled but i don't know why it doesn't show for others. Anyway the direct page links are like https://krishgarg.github.io/(repo name)/

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 --------------------------------------------------------------------------------- Let me know if we can help you further. We always try to provide customer superior service levels, quickly and accurate at the point. I hope I was able to address your query efficiently. NOTE: We are providing high-quality gaming servers for you at a discounted price during the lockdown. To avail the offer, please visit our website and compare plans. Regards,Naman VratiWordPress Freelancer and Cloud Management Engineer - Founder of Team ELITES Org.https://namanvrati.cf/
